### ISSUE TITLE
Problems with enchanting and customsorting

### ISSUE THREAD

**Issue by Hosq** [laytya/AdvancedTradeSkillWindow-vanilla#1]
When i log in and open enchanting tab it looks like this
https://puu.sh/ubz0a/7e46a857da.jpg
and when i first open engineering and then enchanting it then it looks like this
https://puu.sh/ubyWH/411bf949a6.jpg
and when switching back and forth between enchanting and engi the skill name dissappears sometimes
https://puu.sh/ubyX7/82d8394494.jpg

**Comment by laytya** [comment]
just change custom sorting to other sorting or make custom sorting by pressing edit button

**Comment by laytya** [comment]
how to reproduce it step by step?

**Comment by Hosq** [comment]
Seems to work fine without the customsorting but when its enabled i start having problems.
Also found a new error when pressing the edit button for the first time and not having any categories
https://puu.sh/udzRe/d6c25bf312.jpg
and another error when trying to delete a category
http://puu.sh/udAms/fa83bf5f2b.jpg

**Comment by laytya** [comment]
i cant confirm that errors =(

try logoff -  delete saved variables in WTF folder
