### ISSUE TITLE
level of skill

### ISSUE THREAD

**Issue by ldrancer** [laytya/AdvancedTradeSkillWindow-vanilla#11]
i get a bug were it says im say level 45 tailoring, but if i check my character sheet, he's one above it
another bug ill add here as well, it crashes my game sometimes, and almost locks up my computer since ive been using this addon. 
also, processing queue and the other buttons dont seem to work right sometimes.  just seems sort of bugged altogether in its function and needs checked over.

**Comment by Road-block** [comment]
ATSW works off the cache if you just cleared your WDB after a new patch or if you're regularly doing that because you're using the same client to play on different servers or if you have used any of the multitude of tricks to make WDB readonly then this is what will happen.
