### ISSUE TITLE
Spell Reagent Cost Compatibility with AUX

### ISSUE THREAD

**Issue by Zeromark30** [laytya/AdvancedTradeSkillWindow-vanilla#12]
Is there any way you could rename your Reagent Label back to the default string so it stays compatible with AUX pricing for reagents?

AUX CODE: located in crafting.lua
`TradeSkillReagentLabel:SetText(SPELL_REAGENTS .. ' ' .. cost_label(total_cost))`

ATSW CODE:
`<FontString name="ATSWReagentLabel" inherits="GameFontNormalSmall" text="SPELL_REAGENTS">`

Changing AUX code to ATSWReagentLabel provides the expected result

**Comment by laytya** [comment]
im not understand what u talking about. Please add some screens plx.

**Comment by geojak** [comment]
![image](https://user-images.githubusercontent.com/25199983/160607561-19f3dd8b-b4eb-4bd9-9b0e-5700ce925a39.png)

**Comment by geojak** [comment]
he was talking about aux total mat cost display, and you can add it back when you change in the aux code like described by op 

![image](https://user-images.githubusercontent.com/25199983/160607712-314ee99b-2daf-4651-892a-8768b86aa32d.png)

**Comment by geojak** [comment]
The compabiltiy needs to be done by aux thought

**Comment by geojak** [comment]
You can close this, aux has now combabiliry
