### ISSUE TITLE
CLAXXIC PLEASE?

### ISSUE THREAD

**Issue by kschir** [laytya/AdvancedTradeSkillWindow-vanilla#13]

**Comment by ghost** [comment]
Would love ATSW for Classic 
+1 from me

**Comment by DavidBabel** [comment]
+1

**Comment by laytya** [comment]
im using TSM - complete replacement
try it

**Comment by ghost** [comment]
tried it & didnt like it
ATSM 4 Life!

**Comment by darkcloud784** [comment]
+2 (Me and my Wife)

**Comment by alecjpav** [comment]
> im using TSM - complete replacement
> try it

Not a fan personally. Do you have any plans to make a Classic version of ATSW or know of any other addons besides TSM that are similar? Thanks!

**Comment by laytya** [comment]
TSM is more better than ATSW just try it...
It connect all the things u need to craft, store, mail and sell
very usefull

**Comment by alecjpav** [comment]
> TSM is more better than ATSW just try it...
> It connect all the things u need to craft, store, mail and sell
> very usefull

I  did try it. I don't need all that advanced functionality, I didn't really like the UI and mainly I sorely miss how with ATSW you could craft items that requires you to craft other items first automatically with one click of a button. With TSM you have to search each item, add each item to queue, then search and add the item that requires them all, then press craft next every time you move onto the next item. That's only slightly more convenient than doing manually in the default Blizzard window. How ATSW did it was so great.
