### ISSUE TITLE
Advanced Trade Skill Window 2

### ISSUE THREAD

**Issue by Shellyoung** [laytya/AdvancedTradeSkillWindow-vanilla#18]
Hello. I modified this addon into the new version. Check it out. I can take the addon support on me from now.
https://github.com/Shellyoung/Advanced-Trade-Skill-Window

**Comment by laytya** [comment]
Good work. 
need some testing and compatibility testing - but very good for now
about settings - why console command in 2022? use fubar at least
or even ace3 gui

**Comment by Shellyoung** [comment]
I can't find a place for the settings button in the interface. The addon use in-game functions only, no external libraries.

**Comment by laytya** [comment]
good place between close button and skill points - make gear icon

**Comment by Shellyoung** [comment]
No. This is the place for rank (skill) bar.
