### ISSUE TITLE
Process Queue

### ISSUE THREAD

**Issue by brolernus** [laytya/AdvancedTradeSkillWindow-vanilla#2]
it somehow got stuck at processing something and never finishes. now it won't process anything newly added. 
![process](https://cloud.githubusercontent.com/assets/24928956/23137128/9283549c-f7a0-11e6-8072-5686cc6c92e3.PNG)
havent been able to stop the process without relogging.
either add the "stop processing" again or close the process when closing the tradeskill window

(another minor detail i noticed is when processing it disables/grey out the "process queue" + "empty queue",but if you click the "continue process" button the "empty queue" doesnt get disabled again)

**Comment by laytya** [comment]
i found that problem, will fix in next release
