### ISSUE TITLE
Enchanting level displayed incorrectly

### ISSUE THREAD

**Issue by refaim** [laytya/AdvancedTradeSkillWindow-vanilla#20]
1) Open ATSW for Enchanting
2) Enchant something to increase level of enchanting
3) Observe system message in chat "Your skill in enchanting has increased to N"
4) Observe profession level bar in ATSW that still displays N - 1 as level

**Comment by laytya** [comment]
Its known limitation of client not a bug. Just reopen TradeskillFrame

**Comment by refaim** [comment]
Vanilla CraftFrame (that is used for Enchanting) does not suffer from this issue.
