### ISSUE TITLE
[question] Pauses between different items in queue

### ISSUE THREAD

**Issue by theoden-dd** [laytya/AdvancedTradeSkillWindow-vanilla#4]
When I add craft of *different* items to the queue, e.g. "smelt iron" then "smelt tin",
processing queue pauses after every queue element (not every item produced).
So I have to press "Continue queue" to continue with tin in my example.

Is that a requirement in classic wow?

Tested in 0.5.5

**Comment by laytya** [comment]
yes. Its required to push button for each item
